CREATE TABLE tasks (
 id VARCHAR(36) PRIMARY KEY,
 config LONGTEXT NOT NULL,
 updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
);
CREATE TABLE runs (
 id VARCHAR(36) PRIMARY KEY,
 task_id VARCHAR(36) NOT NULL,
 status VARCHAR(32) NOT NULL,
 snapshot LONGTEXT NOT NULL,
 progress LONGTEXT NOT NULL,
 error TEXT NULL,
 cancel_requested BOOLEAN NOT NULL DEFAULT FALSE,
 tokens BIGINT UNSIGNED NOT NULL DEFAULT 0,
 cost DOUBLE NOT NULL DEFAULT 0,
 created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
 INDEX runs_task (task_id), INDEX runs_status (status)
);
CREATE TABLE events (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 run_id VARCHAR(36) NOT NULL,
 kind VARCHAR(40) NOT NULL,
 data LONGTEXT NOT NULL,
 created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 INDEX events_run (run_id, id)
);
CREATE TABLE checkpoints (
 run_id VARCHAR(36) NOT NULL,
 step VARCHAR(160) NOT NULL,
 data LONGTEXT NOT NULL,
 PRIMARY KEY (run_id, step)
);
CREATE TABLE parse_cache (
 hash VARCHAR(100) PRIMARY KEY,
 data LONGTEXT NOT NULL,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE files (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 run_id VARCHAR(36) NOT NULL,
 path TEXT NOT NULL,
 snapshot_path TEXT NOT NULL,
 hash CHAR(64) NOT NULL,
 language VARCHAR(32) NOT NULL,
 status VARCHAR(32) NOT NULL,
 detail TEXT NOT NULL,
 INDEX files_run (run_id, id)
);
CREATE TABLE chunks (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 run_id VARCHAR(36) NOT NULL,
 file_id BIGINT UNSIGNED NOT NULL,
 path TEXT NOT NULL,
 start_line INT UNSIGNED NOT NULL,
 end_line INT UNSIGNED NOT NULL,
 symbols TEXT NOT NULL,
 content MEDIUMTEXT NOT NULL,
 INDEX chunks_run (run_id, id)
);
CREATE TABLE llm_cache (
 hash CHAR(64) PRIMARY KEY,
 data MEDIUMTEXT NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE artifacts (
 id VARCHAR(36) PRIMARY KEY,
 run_id VARCHAR(36) NOT NULL,
 task_id VARCHAR(36) NOT NULL,
 path TEXT NOT NULL,
 hash CHAR(64) NOT NULL,
 markdown LONGTEXT NOT NULL,
 warnings LONGTEXT NOT NULL,
 created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 INDEX artifacts_task (task_id, created_at)
);
CREATE TABLE app_settings (
 id INT PRIMARY KEY,
 data LONGTEXT NOT NULL
);
