/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/runs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["runs_list"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runs/{id}/cancel": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["cancel_run"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runs/{id}/graph": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["graph"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runs/{id}/outline": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["outline"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runs/{id}/outline/continue": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["continue_outline"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runs/{id}/outline/revisions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["revise"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runs/{id}/resume": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["resume_run"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runs/{id}/understanding": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["understanding"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/settings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["settings_get"];
    put: operations["settings_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/tasks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["tasks_list"];
    put?: never;
    post: operations["tasks_save"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/tasks/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["task_delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/tasks/{id}/run": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["start_run"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Approval: {
      /** Format: int32 */
      revision: number;
    };
    /** @description A part of the source the plan deliberately leaves out, and why. */
    BranchExclusion: {
      branch: string;
      reason: string;
    };
    DbConfig: {
      /** @default doccraft_agent */
      database: string;
      /** @default 127.0.0.1 */
      host: string;
      /**
       * Format: int32
       * @default 8
       */
      max_connections: number;
      /** @default  */
      password: string;
      /**
       * Format: int32
       * @default 3306
       */
      port: number;
      /** @default false */
      tls: boolean;
      /** @default root */
      user: string;
    };
    EventView: {
      data: unknown;
      /** Format: int64 */
      id: number;
      kind: string;
      run_id: string;
    };
    Issue: {
      message: string;
      query?: string;
      section: number;
      severity: string;
    };
    LlmConfig: {
      /** @default  */
      api_key: string;
      /** @default http://127.0.0.1:8000/v1 */
      base_url: string;
      /** @default  */
      ca_path: string;
      /** @default 2 */
      concurrency: number;
      /**
       * Format: int32
       * @default 200000
       */
      context_limit: number;
      /** @default medium */
      effort: string;
      /**
       * Format: double
       * @default 0
       */
      input_price: number;
      /**
       * Format: int32
       * @default 16384
       */
      max_output_tokens: number;
      /** @default  */
      model: string;
      /**
       * Format: int32
       * @default 200000
       */
      model_context_limit: number;
      /**
       * Format: int32
       * @default 32768
       */
      model_max_output: number;
      /** @default max_completion_tokens */
      output_parameter: string;
      /**
       * Format: double
       * @default 0
       */
      output_price: number;
      /** @default none */
      proxy_mode: string;
      /** @default  */
      proxy_password: string;
      /** @default  */
      proxy_url: string;
      /** @default  */
      proxy_user: string;
      /** @default off */
      reasoning: string;
      /** @default reasoning_effort */
      reasoning_parameter: string;
      /**
       * Format: int32
       * @default 3
       */
      retries: number;
      /**
       * Format: int32
       * @default 30
       */
      rpm: number;
      /**
       * Format: int32
       * @default 20
       */
      safety_percent: number;
      /**
       * Format: int64
       * @default 180
       */
      timeout_seconds: number;
      /** @default  */
      token_count_url: string;
      /** @default estimate */
      token_mode: string;
      /**
       * Format: int32
       * @default 300000
       */
      tpm: number;
    };
    Outline: {
      /**
       * @description Parts of the source the purpose does not need, named so an omission and a
       *     decision can be told apart.
       */
      excluded_branches?: components["schemas"]["BranchExclusion"][];
      reader_goal?: string;
      requirements?: components["schemas"]["Requirement"][];
      /** Format: int32 */
      revision?: number;
      sections: components["schemas"]["SectionPlan"][];
      storyline?: string;
      terminology?: string[];
    };
    Requirement: {
      id: string;
      question: string;
    };
    Revision: {
      /** Format: int32 */
      base_revision: number;
      feedback?: string | null;
      outline?: null | components["schemas"]["Outline"];
      request_id: string;
    };
    RunId: {
      id: string;
    };
    RunView: {
      /** Format: double */
      cost: number;
      created_at: string;
      error?: string | null;
      id: string;
      progress: unknown;
      status: string;
      task_id: string;
      /** Format: int64 */
      tokens: number;
      updated_at: string;
    };
    SectionPlan: {
      /** @description Parts of the source read tree this section covers, by node key. */
      branches?: string[];
      /** @description Reading prerequisites, expressed as earlier zero-based section indices. */
      depends_on?: number[];
      diagrams?: string[] | null;
      /** @description Source passages read before planning, retained for the section writer. */
      evidence_ids?: string[];
      handoff?: string;
      id?: string;
      key_points?: string[];
      out_of_scope?: string[];
      /** @description Retained for old outlines; new plans do not validate ownership. */
      owns_requirement_ids?: string[];
      query: string;
      /** @description Legacy metadata; new outlines organize sections through key_points. */
      reader_question?: string;
      title: string;
    };
    Settings: {
      /**
       * Format: int64
       * @default 1024
       */
      cache_max_mb: number;
      /**
       * @default {
       *       "database": "doccraft_agent",
       *       "host": "127.0.0.1",
       *       "max_connections": 8,
       *       "password": "",
       *       "port": 3306,
       *       "tls": false,
       *       "user": "root"
       *     }
       */
      db: components["schemas"]["DbConfig"];
      /**
       * @default {
       *       "api_key": "",
       *       "base_url": "http://127.0.0.1:8000/v1",
       *       "ca_path": "",
       *       "concurrency": 2,
       *       "context_limit": 200000,
       *       "effort": "medium",
       *       "input_price": 0,
       *       "max_output_tokens": 16384,
       *       "model": "",
       *       "model_context_limit": 200000,
       *       "model_max_output": 32768,
       *       "output_parameter": "max_completion_tokens",
       *       "output_price": 0,
       *       "proxy_mode": "none",
       *       "proxy_password": "",
       *       "proxy_url": "",
       *       "proxy_user": "",
       *       "reasoning": "off",
       *       "reasoning_parameter": "reasoning_effort",
       *       "retries": 3,
       *       "rpm": 30,
       *       "safety_percent": 20,
       *       "timeout_seconds": 180,
       *       "token_count_url": "",
       *       "token_mode": "estimate",
       *       "tpm": 300000
       *     }
       */
      llm: components["schemas"]["LlmConfig"];
      /**
       * Format: int64
       * @default 20971520
       */
      max_file_bytes: number;
      /** @default 2 */
      max_jobs: number;
      /** @default [] */
      output_roots: string[];
      /**
       * Format: int32
       * @default 30
       */
      retention_days: number;
      /** @default [] */
      source_roots: string[];
    };
    TaskConfig: {
      /** @default  */
      direction: string;
      /** @default [] */
      exclude: string[];
      /** @default  */
      id: string;
      /** @default [] */
      include: string[];
      /** @default 한국어 */
      language: string;
      /**
       * Format: double
       * @default 0
       */
      max_cost: number;
      /**
       * Format: int32
       * @default null
       */
      max_diagrams: number | null;
      /**
       * Format: int32
       * @default 3
       */
      max_iterations: number;
      /**
       * Format: int64
       * @default 7200
       */
      max_seconds: number;
      /**
       * Format: int64
       * @default 2000000
       */
      max_tokens: number;
      /** @default  */
      name: string;
      /** @default false */
      preview_outline: boolean;
      /** @default [] */
      sources: string[];
      /** @default  */
      target: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  runs_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunView"][];
        };
      };
    };
  };
  cancel_run: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  graph: {
    parameters: {
      query?: {
        file_id?: number;
        after?: number;
      };
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  outline: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  continue_outline: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Approval"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Stale revision or active run */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  revise: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Revision"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Stale revision or active run */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  resume_run: {
    parameters: {
      query?: {
        /** @description Apply current LLM settings while preserving completed sections and task budget */
        current_llm?: boolean;
        /** @description Apply the saved task token limit explicitly; other run limits stay fixed */
        current_token_limit?: boolean;
        /** @description Apply the saved task review limit so a warning-completed run can continue from its review checkpoints */
        current_review_limit?: boolean;
      };
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunId"];
        };
      };
    };
  };
  understanding: {
    parameters: {
      query?: {
        after?: string;
      };
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  settings_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Settings"];
        };
      };
    };
  };
  settings_put: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Settings"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Settings"];
        };
      };
    };
  };
  tasks_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskConfig"][];
        };
      };
    };
  };
  tasks_save: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TaskConfig"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskConfig"];
        };
      };
    };
  };
  task_delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  start_run: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunId"];
        };
      };
    };
  };
}
